name = "lotery-apiv3"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BEARER_TOKEN = "lt-apiv3-Xk9mP2qR4vW"
PRIMARY_BASE = "https://www.conectate.com.do/loterias/"
FALLBACK_BASE = "https://loteriasamericanas.com/"
COMPANIES_PATH = "mobile-api-new"
DEFAULT_PATH = "mobile-api/v3"
ENABLE_DOCS = "true"
[[rules]]
type = "Text"
globs = ["**/*.md"]
fallbacks = ["**/*.html"]
fallthrough = true