name = "lotery-hn"
main = "worker.js"
compatibility_date = "2024-01-01"

[vars]
BEARER_TOKEN = "lt-apiv3-Xk9mP2qR4vW"
PRIMARY_BASE = "https://loteriasdehonduras.com/"
FALLBACK_BASE = "https://loteriasdehonduras.com/"
COMPANIES_PATH = "mobile-api/v3"
DEFAULT_PATH = "mobile-api/v3"
ENABLE_DOCS = "true"
[[rules]]
type = "Text"
globs = ["**/*.md"]
fallbacks = ["**/*.html"]
fallthrough = true